version: '3'

services:
  iotcon-mongo:
    image: mongo:4.4.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - iotcon-mongo:/var/lib/iotcon-mongo/data
  iotcon-redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - iotcon-redis:/bitnami/redis/data

volumes:
  iotcon-mongo:
  iotcon-redis:
