export enum OperationModesEnum {
  MODULE_CREATE = 'MODULE_CREATE',
  MODULE_CREATE_AND_START = 'MODULE_CREATE_AND_START',
  MODULE_REPLACE = 'MODULE_REPLACE',
  MODULE_START = 'MODULE_START',
  MODULE_STOP = 'MODULE_STOP',
  MODULE_RESTART = 'MODULE_RESTART',
  MODULE_DELETE = 'MODULE_DELETE',
  DELETE_ALL = 'DELETE_ALL',
}
