export enum ModuleTypesEnum {
  CORE_LIB_MODULE = 'CORE_LIB_MODULE',
  IOT_SENSOR = 'IOT_SENSOR',
  IOT_PUBLISHER = 'IOT_PUBLISHER',
  IOTCON_COLLECTOR = 'IOTCON_COLLECTOR',
  IOTCON_PUBLISHER = 'IOTCON_PUBLISHER',
}
